[base]
code_size = 6
port = 8080
bearer_token = "CrGNF75kBN"

[database]
database_type = "sqlite"
database = "swiftlink.db" # Path to the SQLite database file
max_connections = 12

# [database]
# database_type = "postgres"
# username = "swiftlink"
# password = "archbtw"
# host = "localhost"
# port = 5432
# database = "swiftlink_db"
# max_connections = 12
