[package]
name = "swiftclient"
version = "0.0.2"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
swiftlink-api = { path = "../swiftlink-api", features = ["blocking"] }
