name: Build and Deploy mdBook Docs to VPS

on:
  push:
    branches:
      - pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v6

      - name: Build MkDocs
        run: |
          pip install mkdocs mkdocs-material
          mkdocs build --config-file docs/mkdocs.yml

      - name: Assemble site
        run: |
          rm -rf dist
          mkdir -p dist/d
          cp -r site/* dist/
          cp -r public/docs/* dist/d/

      # Deploy to VPS over SSH
      - name: Deploy to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: actions
          key: ${{ secrets.VPS_PRIV_KEY }}
          port: 22
          source: "dist/"
          target: "/home/actions/swiftlink"
          rm: true
